import { writeFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import { ArtSvg, arts } from "../components/work/art-source";
import type { ArtKind } from "../data/projects";

const out: Record<string, string> = {};
for (const kind of Object.keys(arts) as ArtKind[]) {
  out[`${kind}:d`] = renderToStaticMarkup(<ArtSvg kind={kind} decorative />);
  out[`${kind}:l`] = renderToStaticMarkup(<ArtSvg kind={kind} decorative={false} />);
}

const body = `// Generated by scripts/generate-art.tsx. Do not edit by hand. Run \`npm run art\`.\nexport const artMarkup: Record<string, string> = ${JSON.stringify(out, null, 1)};\n`;
writeFileSync(new URL("../components/work/art-markup.generated.ts", import.meta.url), body);
console.log(`Wrote ${Object.keys(out).length} SVGs (${Math.round(body.length / 1024)} KB)`);
